#!/bin/bash

export POSIXLY_CORRECT=yes

regex1='([0-9]{4})-([0-2]{2})-([0-9]{2}) ([0-9]{2}:[0-9]{2}:[0-9]{2})'
regex2='([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})'
regex3='([0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4}:[0-9a-fA-F]{1,4})'

if [[ $1 == *"log"* ]]; then
	cat $1
fi
 case $1 in
   "-a")
	beg="$2"
	end="$4"
	if [[ $beg =~ $regex1 ]]; then
	   if [ $5 == "list-uri" ]; then

	   cat $6 | grep "POST\|GET\|HEAD" | awk -v beg="$beg" -v end="$end" '
    		{
	        	split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    		}
   	 	(cur > beg) && (cur < end) {if( $7 != "/" ){print $7}}'

	   elif [ $5 == "list-hosts" ]; then

	   cat $6 | awk -v beg="$beg" -v end="$end" '
    	   {
	        split($4,t,/[[\/:]/)
        	mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        	cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    	   }
   	   (cur > beg) && (cur < end) { system ("host " $1) }' | grep -v "not found:" | sort | uniq | awk -F "domain name pointer" '{print $2}'

	   elif [ $3 == "-b" ]; then

 	   	file="$5"

	   	awk -v beg="$beg" -v end="$end" '
    	   	{
        		split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
       	  		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    	   	}
    	  	 (cur > beg) && (cur < end)
	  	' "$file"

	   else

		file="$3"

		awk -v beg="$beg" '
		    {
		        split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    		}
    		(cur > beg)
		' "$file"
	   fi

	else
	    echo "spatne zadany cas"
	fi
	;;
   "-b")
	beg="$2"
	end="$4"
	if [[ $beg =~ $regex1 ]]; then
		if [ $5 == "list-uri" ]; then

	   cat $6 | grep "POST\|GET\|HEAD" | awk -v end="$beg" -v beg="$end" '
    		{
	        	split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    		}
   	 	(cur > beg) && (cur < end) {if( $7 != "/" ){print $7}}'

		elif [ $5 == "list-hosts" ]; then

	   	cat $6 | awk -v end="$beg" -v beg="$end" '
    	   	{
	        	split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    	   	}
   	   	(cur > beg) && (cur < end) { system ("host " $1) }' | grep -v "not found:" | sort | uniq | awk -F "domain name pointer" '{print $2}'

		elif [ $3 == "-a" ]; then

 	   	file="$5"

	   	awk -v end="$beg" -v beg="$end" '
    	   	{
        		split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
       	  		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    	   	}
    	  	 (cur > beg) && (cur < end)
	  	' "$file"

	   else

		file="$3"

		awk -v beg="$beg" '
		    {
		        split($4,t,/[[\/:]/)
        		mthNr = (index("JanFebMarAprMayJunJulAugSepOctNovDec",t[3])+2)/3
        		cur = sprintf("%04d-%02d-%02d %02d:%02d:%02d",t[4],mthNr,t[2],t[5],t[6],t[7])
    		}
    		(cur < beg)
		' "$file"
	   fi

	else
	   echo "spatne zadany cas"
	fi
	;;
   "-ip")
	arg="$2"
	if [[ $arg =~ $regex2 ]]; then
	   if [ $3 == "list-ip" ]; then
		awk -v "val=$arg" '{if( $1 ~ val ) print val }' $4 | sort | uniq
	   elif [ $3 == "list-uri" ]; then
		cat $4 | grep "POST\|GET\|HEAD" | awk -v "val=$arg" '{if( $1 ~ val ) print $7 }' | sort | uniq
	   else
	   	awk -v "val=$arg" '{if( $1 ~ val ) print val }' $3
	   fi
	elif [[ $arg =~ $regex3 ]]; then
	   if [ $3 == "list-ip" ]; then
		awk -v "val=$arg" '{if( $1 ~ val ) print val }' $4 | sort | uniq
	   elif [ $3 == "list-uri" ]; then
		cat $4 | grep "POST\|GET\|HEAD" | awk -v "val=$arg" '{if( $1 ~ val ) print $7 }' | sort | uniq
	   else
	   	awk -v "val=$arg" '{if( $1 ~ val ) print val }' $3
	   fi
	else
	   echo "spatne zadana ip adresa"
	fi
	;;
   "-uri")
	line="$2"
	cat $3 | grep $line | awk '{print $7}'
	;;
   "list-ip")
	awk '!x[$1]++ {print $1}' $2
	;;
   "list-hosts")
	cat $2 | awk '{ system ("host " $1) }' | grep -v "not found:" | sort | uniq | awk -F "domain name pointer" '{print $2}'
	;;
   "list-uri")
	cat $2 | grep "POST\|GET\|HEAD" | awk '!x[$7]++ {print $7}'
	;;
   "hist-ip")
	awk '{a[$1]++}
     		END { for(i in a) {
             	printf "%s (%d):" ,i,a[i]
             	for(j=0;j<a[i];++j) printf "#"; printf "\n"
           }
     	}' $2 | sort -rn
	;;
   "hist-load")
	;;
esac
